<div class="container-fluid mb-5">
    <div class="row">
        <div class="col-md-9 col-lg-8 col-xl-6">
            <form method="post" enctype="multipart/form-data">
                <input type="hidden" name="product_id" value="<?= $productInfo['product_id'] ?>" />

                <div class="form-group mb-2">
                    <label for="name">Název produktu</label>
                    <input type="text" class="form-control" id="name" name="name" value="<?= $productInfo['name'] ?>" />
                </div>

                <div class="form-group mb-2">
                    <label for="description">Popis produktu</label>
                    <textarea rows="5" class="form-control" id="description" name="description"><?= $productInfo['description'] ?> </textarea>
                </div>

                <div class="form-group mb-2">
                    <label for="price">Cena produktu</label>
                    <div class="input-group">
                        <input type="number" class="form-control" id="price" name="price" value="<?= $productInfo['price'] ?>" />
                        <div class="input-group-append">
                            <span class="input-group-text">Kč</span>
                        </div>
                    </div>
                </div>
                
                <div class="form-group mb-2">
                    <label for="image">Obrázek produktu</label>
                    <div class="input-group">
                        <input type="file" class="form-control" id="image" name="image">
                    </div>
                </div>
                
                <button type="submit" class="btn btn-primary">Vložit produkt</button>

            </form>
        </div>
    </div>
</div>


