<h2 class="mb-5">Detail produktu</h2>

<div class="row">
    <div class="col-lg-6">
        <h3><?= $product['name'] ?></h3>
        <p><?= $product['description'] ?></p>
        <h3><?= $product['price'] ?>,-</h3>

    </div>
    <div class="col-lg-6">
        <img class="img-fluid" src="<?= $product['image_path'] ?>">
    </div>
</div>
<?php if($admin): ?>
<div class="row">
    <div class="text-center">
        <a href="editor/<?= $product['product_id'] ?>">Upravit</a> |
        <a href="products/<?= $product['product_id'] ?>/delete">Odstranit</a>
    </div>
</div>
<?php endif; ?>
