<!doctype html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="utf-8">
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>

    <body style="margin-bottom: 10rem">
        
        <?php foreach ($messages as $message): ?>
            <div class="alert alert-<?= $message['style'] ?>" role="alert">
                <?= $message['message'] ?>
            </div>
        <?php endforeach; ?>

        <div class="w-75 container mb-3">
            <nav class="navbar navbar-expand-md bg-body-tertiary">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="products">Všechny produkty</a>
                        </li>
                    </ul>
                    <form class="d-flex ms-auto" role="search" method="post">
                        <input class="form-control me-2" type="search" name="search" placeholder="Vyhledávání" aria-label="vyhledávání">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </div>


        <div class="container w-75">
            <article>
                <?php $this->controller->renderView(); ?>
            </article>
        </div>    
        <footer class="fixed-bottom mt-5">
            <div class="text-center bg-light p-4" style="background-color: rgba(0, 0, 0, 1);">
                <a href="logIn">Přihlášení</a> |
                <a href="registration">Registrace</a> |
                <a href="administration">Administrace</a>
            </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>